### ISSUE TITLE
Some FlexyPin socket pins are too close to JP6 and JP7 on Nucleo board

### ISSUE THREAD

**Issue by abdullahyildiz** [efabless/caravel_board#24]
JP6 and JP7 on Nucleo board bend the pins on the first breakout board attached. We had to use another set of headers to increase the distance between Nucleo board and Caravel Nucleo Hat.

**Comment by mguthaus** [comment]
I had some similar problems with pins. I'm not sure if this was caused by these jumpers but they are hard to get to connect.

![PXL_20230123_215023017](https://user-images.githubusercontent.com/12450095/214368733-d207cd7c-a334-41fc-a750-024795173bb8.jpg)

![PXL_20230123_215209496](https://user-images.githubusercontent.com/12450095/214368509-01fabb7f-cd6f-41e9-b803-501d69753163.jpg)
